services:
  - type: web
    name: accessibility-rails-components
    runtime: ruby
    plan: free
    region: singapore
    repo: https://github.com/jen-the-dev/accessibility-rails-components
    branch: main
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:prepare
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /health
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_PATH
        value: /tmp/production.sqlite3
